create or replace TABLE T_COMPENSATION (
	SERIES_NUMBER NUMBER(38,0) NOT NULL,
	SERIES_NAME VARCHAR(16777216),
	IS_TURNED_ON BOOLEAN,
	IS_LOCATION_EXCEEDED BOOLEAN,
	IS_LOCATION_ACTIVE BOOLEAN,
	IS_LOCATION_MAINTAINING BOOLEAN,
	LCT_RADIUS NUMBER(38,0),
	LCT_RANGE NUMBER(38,0),
	LCT_FINDER BOOLEAN,
	LCT_LOCKDOWN VARCHAR(16777216)
);